{"uuid": "36826a75-af89-42bb-8459-c667e60af53e", "children": ["0d457233-664e-4bca-85fe-d107a9eb0064", "743e5d90-5cfc-489b-8cc1-0a506d7dc174", "bbd3219e-c0b6-496a-9713-dbd87f25f7fc"], "befores": [{"name": "清理历史数据", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/xuanlonghua/Documents/ZD/Projects/appium_autotest/scripts/result/logs/logcat/'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"/Users/xuanlonghua/Documents/ZD/Projects/appium_autotest/scripts/conftest.py\", line 130, in clear\n    fc.do_clear_logcat()\n  File \"/Users/xuanlonghua/Documents/ZD/Projects/appium_autotest/common/utils/FileClearUtil.py\", line 22, in do_clear_logcat\n    shutil.rmtree(self.logcat_path)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py\", line 516, in rmtree\n    return _rmtree_unsafe(path, onerror)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py\", line 377, in _rmtree_unsafe\n    onerror(os.scandir, path, sys.exc_info())\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py\", line 374, in _rmtree_unsafe\n    with os.scandir(path) as scandir_it:\n"}, "start": 1600594442443, "stop": 1600594442451}], "start": 1600594442443, "stop": 1600594442587}